name: sign_to_speech_app
description: "Parrot - Sign to Speech App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.2.0
  go_router: ^17.0.1
  google_fonts: ^7.0.2
  lucide_icons: ^0.257.0
  state_notifier: ^1.0.0
  socket_io_client: ^3.1.4
  http: ^1.6.0
  audioplayers: ^6.5.1
  file_picker: ^10.3.8
  flutter_tts: ^4.2.5
  record: ^5.1.0
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/brand/logo.jpg
    - assets/icons/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/brand/logo.jpg"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/brand/logo.jpg"
    background_color: "#0175C2"
    theme_color: "#0175C2"
  windows:
    generate: true
    image_path: "assets/brand/logo.jpg"
    icon_size: 48
